# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


LiteralString = str
# -- template models.py.jinja --
from pydantic import BaseModel

from . import fields, actions
from ._types import FuncType
from ._builder import serialize_base64
from ._compat import PYDANTIC_V2, ConfigDict

if TYPE_CHECKING:
    from .client import Prisma


_PrismaModelT = TypeVar('_PrismaModelT', bound='_PrismaModel')


class _PrismaModel(BaseModel):
    if PYDANTIC_V2:
        model_config: ClassVar[ConfigDict] = ConfigDict(
            use_enum_values=True,
            arbitrary_types_allowed=True,
            populate_by_name=True,
        )
    elif not TYPE_CHECKING:
        from ._compat import BaseConfig

        class Config(BaseConfig):
            use_enum_values: bool = True
            arbitrary_types_allowed: bool = True
            allow_population_by_field_name: bool = True
            json_encoders: Dict[Any, FuncType] = {
                fields.Base64: serialize_base64,
            }

    # TODO: ensure this is required by subclasses
    __prisma_model__: ClassVar[str]


class BaseUser(_PrismaModel):
    __prisma_model__: ClassVar[Literal['User']] = 'User'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.UserActions[_PrismaModelT]':
        from .client import get_client

        return actions.UserActions[_PrismaModelT](client or get_client(), cls)


class BaseSkill(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Skill']] = 'Skill'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.SkillActions[_PrismaModelT]':
        from .client import get_client

        return actions.SkillActions[_PrismaModelT](client or get_client(), cls)


class BaseSkillAlias(_PrismaModel):
    __prisma_model__: ClassVar[Literal['SkillAlias']] = 'SkillAlias'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.SkillAliasActions[_PrismaModelT]':
        from .client import get_client

        return actions.SkillAliasActions[_PrismaModelT](client or get_client(), cls)


class BaseJobRole(_PrismaModel):
    __prisma_model__: ClassVar[Literal['JobRole']] = 'JobRole'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.JobRoleActions[_PrismaModelT]':
        from .client import get_client

        return actions.JobRoleActions[_PrismaModelT](client or get_client(), cls)


class BaseJobSkill(_PrismaModel):
    __prisma_model__: ClassVar[Literal['JobSkill']] = 'JobSkill'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.JobSkillActions[_PrismaModelT]':
        from .client import get_client

        return actions.JobSkillActions[_PrismaModelT](client or get_client(), cls)


class BaseResume(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Resume']] = 'Resume'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.ResumeActions[_PrismaModelT]':
        from .client import get_client

        return actions.ResumeActions[_PrismaModelT](client or get_client(), cls)


class BaseCandidateEnrichment(_PrismaModel):
    __prisma_model__: ClassVar[Literal['CandidateEnrichment']] = 'CandidateEnrichment'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.CandidateEnrichmentActions[_PrismaModelT]':
        from .client import get_client

        return actions.CandidateEnrichmentActions[_PrismaModelT](client or get_client(), cls)


class BaseAnalysis(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Analysis']] = 'Analysis'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.AnalysisActions[_PrismaModelT]':
        from .client import get_client

        return actions.AnalysisActions[_PrismaModelT](client or get_client(), cls)


class BaseChat(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Chat']] = 'Chat'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.ChatActions[_PrismaModelT]':
        from .client import get_client

        return actions.ChatActions[_PrismaModelT](client or get_client(), cls)


class BaseChatMessage(_PrismaModel):
    __prisma_model__: ClassVar[Literal['ChatMessage']] = 'ChatMessage'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.ChatMessageActions[_PrismaModelT]':
        from .client import get_client

        return actions.ChatMessageActions[_PrismaModelT](client or get_client(), cls)


