# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off
from __future__ import annotations

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


LiteralString = str
# -- template client.py.jinja --
import warnings
import logging
from datetime import timedelta
from pathlib import Path
from types import TracebackType
from typing_extensions import override

from pydantic import BaseModel

from . import types, models, errors, actions
from ._base_client import BasePrisma, UseClientDefault, USE_CLIENT_DEFAULT
from .types import DatasourceOverride, HttpConfig, MetricsFormat
from ._types import BaseModelT, PrismaMethod, TransactionId, Datasource
from .bases import _PrismaModel
from ._builder import QueryBuilder, dumps
from .generator.models import EngineType, OptionalValueFromEnvVar, BinaryPaths
from ._compat import removeprefix, model_parse
from ._constants import CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED, DEFAULT_CONNECT_TIMEOUT, DEFAULT_TX_MAX_WAIT, DEFAULT_TX_TIMEOUT
from ._raw_query import deserialize_raw_results
from ._metrics import Metrics
from .metadata import PRISMA_MODELS, RELATIONAL_FIELD_MAPPINGS
from ._transactions import AsyncTransactionManager, SyncTransactionManager

# re-exports
from ._base_client import SyncBasePrisma, AsyncBasePrisma, load_env as load_env
from ._registry import (
    register as register,
    get_client as get_client,
    RegisteredClient as RegisteredClient,
)


__all__ = (
    'ENGINE_TYPE',
    'SCHEMA_PATH',
    'BINARY_PATHS',
    'Batch',
    'Prisma',
    'Client',
    'load_env',
    'register',
    'get_client',
)

log: logging.Logger = logging.getLogger(__name__)

SCHEMA_PATH = Path('C:/Desktop file/2026/resume_scanner/resume-scanner/backend/prisma/schema.prisma')
PACKAGED_SCHEMA_PATH = Path(__file__).parent.joinpath('schema.prisma')
ENGINE_TYPE: EngineType = EngineType.binary
BINARY_PATHS = model_parse(BinaryPaths, {'queryEngine': {'windows': 'C:\\Users\\kansa\\.cache\\prisma-python\\binaries\\5.17.0\\393aa359c9ad4a4bb28630fb5613f9c281cde053\\node_modules\\prisma\\query-engine-windows.exe'}, 'introspectionEngine': {}, 'migrationEngine': {}, 'libqueryEngine': {}, 'prismaFmt': {}})


class Prisma(AsyncBasePrisma):
    # Note: these property names can be customised using `/// @Python(instance_name: '...')`
    # https://prisma-client-py.readthedocs.io/en/stable/reference/schema-extensions/#instance_name
    user: 'actions.UserActions[models.User]'
    skill: 'actions.SkillActions[models.Skill]'
    skillalias: 'actions.SkillAliasActions[models.SkillAlias]'
    jobrole: 'actions.JobRoleActions[models.JobRole]'
    jobskill: 'actions.JobSkillActions[models.JobSkill]'
    resume: 'actions.ResumeActions[models.Resume]'
    candidateenrichment: 'actions.CandidateEnrichmentActions[models.CandidateEnrichment]'
    analysis: 'actions.AnalysisActions[models.Analysis]'
    chat: 'actions.ChatActions[models.Chat]'
    chatmessage: 'actions.ChatMessageActions[models.ChatMessage]'

    __slots__ = (
        'user',
        'skill',
        'skillalias',
        'jobrole',
        'jobskill',
        'resume',
        'candidateenrichment',
        'analysis',
        'chat',
        'chatmessage',
    )

    def __init__(
        self,
        *,
        use_dotenv: bool = True,
        log_queries: bool = False,
        auto_register: bool = False,
        datasource: DatasourceOverride | None = None,
        connect_timeout: int | timedelta = DEFAULT_CONNECT_TIMEOUT,
        http: HttpConfig | None = None,
    ) -> None:
        super().__init__(
            http=http,
            use_dotenv=use_dotenv,
            log_queries=log_queries,
            datasource=datasource,
            connect_timeout=connect_timeout,
        )
        self._set_generated_properties(
            schema_path=SCHEMA_PATH,
            engine_type=ENGINE_TYPE,
            prisma_models=PRISMA_MODELS,
            packaged_schema_path=PACKAGED_SCHEMA_PATH,
            relational_field_mappings=RELATIONAL_FIELD_MAPPINGS,
            preview_features=set([]),
            active_provider='postgresql',
            default_datasource_name='db',
        )

        self.user = actions.UserActions[models.User](self, models.User)
        self.skill = actions.SkillActions[models.Skill](self, models.Skill)
        self.skillalias = actions.SkillAliasActions[models.SkillAlias](self, models.SkillAlias)
        self.jobrole = actions.JobRoleActions[models.JobRole](self, models.JobRole)
        self.jobskill = actions.JobSkillActions[models.JobSkill](self, models.JobSkill)
        self.resume = actions.ResumeActions[models.Resume](self, models.Resume)
        self.candidateenrichment = actions.CandidateEnrichmentActions[models.CandidateEnrichment](self, models.CandidateEnrichment)
        self.analysis = actions.AnalysisActions[models.Analysis](self, models.Analysis)
        self.chat = actions.ChatActions[models.Chat](self, models.Chat)
        self.chatmessage = actions.ChatMessageActions[models.ChatMessage](self, models.ChatMessage)

        if auto_register:
            register(self)

    @property
    @override
    def _default_datasource(self) -> Datasource:
        return {
            'name': 'db',
            'url': OptionalValueFromEnvVar(**{'value': None, 'fromEnvVar': 'DATABASE_URL'}).resolve(),
            'source_file_path': 'C:/Desktop file/2026/resume_scanner/resume-scanner/backend/prisma/schema.prisma',
        }

    async def execute_raw(self, query: LiteralString, *args: Any) -> int:
        resp = await self._execute(
            method='execute_raw',
            arguments={
                'query': query,
                'parameters': args,
            },
            model=None,
        )
        return int(resp['data']['result'])

    @overload
    async def query_first(
        self,
        query: LiteralString,
        *args: Any,
    ) -> dict[str, Any]:
        ...

    @overload
    async def query_first(
        self,
        query: LiteralString,
        *args: Any,
        model: Type[BaseModelT],
    ) -> Optional[BaseModelT]:
        ...

    async def query_first(
        self,
        query: LiteralString,
        *args: Any,
        model: Optional[Type[BaseModelT]] = None,
    ) -> Union[Optional[BaseModelT], dict[str, Any]]:
        """This function is the exact same as `query_raw()` but returns the first result.

        If model is given, the returned record is converted to the pydantic model first,
        otherwise a raw dictionary will be returned.
        """
        results: Sequence[Union[BaseModelT, dict[str, Any]]]
        if model is not None:
            results = await self.query_raw(query, *args, model=model)
        else:
            results = await self.query_raw(query, *args)

        if not results:
            return None

        return results[0]

    @overload
    async def query_raw(
        self,
        query: LiteralString,
        *args: Any,
    ) -> List[dict[str, Any]]:
        ...

    @overload
    async def query_raw(
        self,
        query: LiteralString,
        *args: Any,
        model: Type[BaseModelT],
    ) -> List[BaseModelT]:
        ...

    async def query_raw(
        self,
        query: LiteralString,
        *args: Any,
        model: Optional[Type[BaseModelT]] = None,
    ) -> Union[List[BaseModelT], List[dict[str, Any]]]:
        """Execute a raw SQL query against the database.

        If model is given, each returned record is converted to the pydantic model first,
        otherwise results will be raw dictionaries.
        """
        resp = await self._execute(
            method='query_raw',
            arguments={
                'query': query,
                'parameters': args,
            },
            model=model,
        )
        result = resp['data']['result']
        if model is not None:
            return deserialize_raw_results(result, model=model)

        return deserialize_raw_results(result)

    def batch_(self) -> Batch:
        """Returns a context manager for grouping write queries into a single transaction."""
        return Batch(client=self)

    def tx(
        self,
        *,
        max_wait: Union[int, timedelta] = DEFAULT_TX_MAX_WAIT,
        timeout: Union[int, timedelta] = DEFAULT_TX_TIMEOUT,
    ) -> TransactionManager:
        """Returns a context manager for executing queries within a database transaction.

        Entering the context manager returns a new Prisma instance wrapping all
        actions within a transaction, queries will be isolated to the Prisma instance and
        will not be commited to the database until the context manager exits.

        By default, Prisma will wait a maximum of 2 seconds to acquire a transaction from the database. You can modify this
        default with the `max_wait` argument which accepts a value in milliseconds or `datetime.timedelta`.

        By default, Prisma will cancel and rollback ay transactions that last longer than 5 seconds. You can modify this timeout
        with the `timeout` argument which accepts a value in milliseconds or `datetime.timedelta`.

        Example usage:

        ```py
        async with client.tx() as transaction:
            user1 = await client.user.create({'name': 'Robert'})
            user2 = await client.user.create({'name': 'Tegan'})
        ```

        In the above example, if the first database call succeeds but the second does not then neither of the records will be created.
        """
        return TransactionManager(
            client=self,
            max_wait=max_wait,
            timeout=timeout,
        )


TransactionManager = AsyncTransactionManager[Prisma]


# TODO: this should return the results as well
# TODO: don't require copy-pasting arguments between actions and batch actions
class Batch:
    user: 'UserBatchActions'
    skill: 'SkillBatchActions'
    skillalias: 'SkillAliasBatchActions'
    jobrole: 'JobRoleBatchActions'
    jobskill: 'JobSkillBatchActions'
    resume: 'ResumeBatchActions'
    candidateenrichment: 'CandidateEnrichmentBatchActions'
    analysis: 'AnalysisBatchActions'
    chat: 'ChatBatchActions'
    chatmessage: 'ChatMessageBatchActions'

    def __init__(self, client: Prisma) -> None:
        self.__client = client
        self.__queries: List[str] = []
        self._active_provider = client._active_provider
        self.user = UserBatchActions(self)
        self.skill = SkillBatchActions(self)
        self.skillalias = SkillAliasBatchActions(self)
        self.jobrole = JobRoleBatchActions(self)
        self.jobskill = JobSkillBatchActions(self)
        self.resume = ResumeBatchActions(self)
        self.candidateenrichment = CandidateEnrichmentBatchActions(self)
        self.analysis = AnalysisBatchActions(self)
        self.chat = ChatBatchActions(self)
        self.chatmessage = ChatMessageBatchActions(self)

    def _add(self, **kwargs: Any) -> None:
        builder = QueryBuilder(
            **kwargs,
            prisma_models=PRISMA_MODELS,
            relational_field_mappings=RELATIONAL_FIELD_MAPPINGS,
        )
        self.__queries.append(builder.build_query())

    async def commit(self) -> None:
        """Execute the queries"""
        # TODO: normalise this, we should still call client._execute
        queries = self.__queries
        self.__queries = []

        payload = {
            'batch': [
                {
                    'query': query,
                    'variables': {},
                }
                for query in queries
            ],
            'transaction': True,
        }
        await self.__client._engine.query(
            dumps(payload),
            tx_id=self.__client._tx_id,
        )

    def execute_raw(self, query: LiteralString, *args: Any) -> None:
        self._add(
            method='execute_raw',
            arguments={
                'query': query,
                'parameters': args,
            }
        )

    async def __aenter__(self) -> 'Batch':
        return self

    async def __aexit__(
        self,
        exc_type: Optional[Type[BaseException]],
        exc: Optional[BaseException],
        exc_tb: Optional[TracebackType],
    ) -> None:
        if exc is None:
            await self.commit()


# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class UserBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.UserCreateInput,
        include: Optional[types.UserInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.User,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.UserCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.User,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.UserWhereUniqueInput,
        include: Optional[types.UserInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.User,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.UserUpdateInput,
        where: types.UserWhereUniqueInput,
        include: Optional[types.UserInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.User,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.UserWhereUniqueInput,
        data: types.UserUpsertInput,
        include: Optional[types.UserInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.User,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.UserUpdateManyMutationInput,
        where: types.UserWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.User,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.UserWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.User,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class SkillBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.SkillCreateInput,
        include: Optional[types.SkillInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.Skill,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.SkillCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.Skill,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.SkillWhereUniqueInput,
        include: Optional[types.SkillInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.Skill,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.SkillUpdateInput,
        where: types.SkillWhereUniqueInput,
        include: Optional[types.SkillInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.Skill,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.SkillWhereUniqueInput,
        data: types.SkillUpsertInput,
        include: Optional[types.SkillInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.Skill,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.SkillUpdateManyMutationInput,
        where: types.SkillWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.Skill,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.SkillWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.Skill,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class SkillAliasBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.SkillAliasCreateInput,
        include: Optional[types.SkillAliasInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.SkillAlias,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.SkillAliasCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.SkillAlias,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.SkillAliasWhereUniqueInput,
        include: Optional[types.SkillAliasInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.SkillAlias,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.SkillAliasUpdateInput,
        where: types.SkillAliasWhereUniqueInput,
        include: Optional[types.SkillAliasInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.SkillAlias,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.SkillAliasWhereUniqueInput,
        data: types.SkillAliasUpsertInput,
        include: Optional[types.SkillAliasInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.SkillAlias,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.SkillAliasUpdateManyMutationInput,
        where: types.SkillAliasWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.SkillAlias,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.SkillAliasWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.SkillAlias,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class JobRoleBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.JobRoleCreateInput,
        include: Optional[types.JobRoleInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.JobRole,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.JobRoleCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.JobRole,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.JobRoleWhereUniqueInput,
        include: Optional[types.JobRoleInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.JobRole,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.JobRoleUpdateInput,
        where: types.JobRoleWhereUniqueInput,
        include: Optional[types.JobRoleInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.JobRole,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.JobRoleWhereUniqueInput,
        data: types.JobRoleUpsertInput,
        include: Optional[types.JobRoleInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.JobRole,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.JobRoleUpdateManyMutationInput,
        where: types.JobRoleWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.JobRole,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.JobRoleWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.JobRole,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class JobSkillBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.JobSkillCreateInput,
        include: Optional[types.JobSkillInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.JobSkill,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.JobSkillCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.JobSkill,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.JobSkillWhereUniqueInput,
        include: Optional[types.JobSkillInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.JobSkill,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.JobSkillUpdateInput,
        where: types.JobSkillWhereUniqueInput,
        include: Optional[types.JobSkillInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.JobSkill,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.JobSkillWhereUniqueInput,
        data: types.JobSkillUpsertInput,
        include: Optional[types.JobSkillInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.JobSkill,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.JobSkillUpdateManyMutationInput,
        where: types.JobSkillWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.JobSkill,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.JobSkillWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.JobSkill,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class ResumeBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.ResumeCreateInput,
        include: Optional[types.ResumeInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.Resume,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.ResumeCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.Resume,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.ResumeWhereUniqueInput,
        include: Optional[types.ResumeInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.Resume,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.ResumeUpdateInput,
        where: types.ResumeWhereUniqueInput,
        include: Optional[types.ResumeInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.Resume,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.ResumeWhereUniqueInput,
        data: types.ResumeUpsertInput,
        include: Optional[types.ResumeInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.Resume,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.ResumeUpdateManyMutationInput,
        where: types.ResumeWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.Resume,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.ResumeWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.Resume,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class CandidateEnrichmentBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.CandidateEnrichmentCreateInput,
        include: Optional[types.CandidateEnrichmentInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.CandidateEnrichment,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.CandidateEnrichmentCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.CandidateEnrichment,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.CandidateEnrichmentWhereUniqueInput,
        include: Optional[types.CandidateEnrichmentInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.CandidateEnrichment,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.CandidateEnrichmentUpdateInput,
        where: types.CandidateEnrichmentWhereUniqueInput,
        include: Optional[types.CandidateEnrichmentInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.CandidateEnrichment,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.CandidateEnrichmentWhereUniqueInput,
        data: types.CandidateEnrichmentUpsertInput,
        include: Optional[types.CandidateEnrichmentInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.CandidateEnrichment,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.CandidateEnrichmentUpdateManyMutationInput,
        where: types.CandidateEnrichmentWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.CandidateEnrichment,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.CandidateEnrichmentWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.CandidateEnrichment,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class AnalysisBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.AnalysisCreateInput,
        include: Optional[types.AnalysisInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.Analysis,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.AnalysisCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.Analysis,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.AnalysisWhereUniqueInput,
        include: Optional[types.AnalysisInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.Analysis,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.AnalysisUpdateInput,
        where: types.AnalysisWhereUniqueInput,
        include: Optional[types.AnalysisInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.Analysis,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.AnalysisWhereUniqueInput,
        data: types.AnalysisUpsertInput,
        include: Optional[types.AnalysisInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.Analysis,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.AnalysisUpdateManyMutationInput,
        where: types.AnalysisWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.Analysis,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.AnalysisWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.Analysis,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class ChatBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.ChatCreateInput,
        include: Optional[types.ChatInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.Chat,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.ChatCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.Chat,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.ChatWhereUniqueInput,
        include: Optional[types.ChatInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.Chat,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.ChatUpdateInput,
        where: types.ChatWhereUniqueInput,
        include: Optional[types.ChatInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.Chat,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.ChatWhereUniqueInput,
        data: types.ChatUpsertInput,
        include: Optional[types.ChatInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.Chat,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.ChatUpdateManyMutationInput,
        where: types.ChatWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.Chat,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.ChatWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.Chat,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class ChatMessageBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.ChatMessageCreateInput,
        include: Optional[types.ChatMessageInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.ChatMessage,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.ChatMessageCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.ChatMessage,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.ChatMessageWhereUniqueInput,
        include: Optional[types.ChatMessageInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.ChatMessage,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.ChatMessageUpdateInput,
        where: types.ChatMessageWhereUniqueInput,
        include: Optional[types.ChatMessageInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.ChatMessage,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.ChatMessageWhereUniqueInput,
        data: types.ChatMessageUpsertInput,
        include: Optional[types.ChatMessageInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.ChatMessage,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.ChatMessageUpdateManyMutationInput,
        where: types.ChatMessageWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.ChatMessage,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.ChatMessageWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.ChatMessage,
            arguments={'where': where},
            root_selection=['count'],
        )



Client = Prisma