from __future__ import annotations
# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# fmt: off
# -- template metadata.py.jinja --


PRISMA_MODELS: set[str] = {
    'User',
    'Skill',
    'SkillAlias',
    'JobRole',
    'JobSkill',
    'Resume',
    'CandidateEnrichment',
    'Analysis',
    'Chat',
    'ChatMessage',
}

RELATIONAL_FIELD_MAPPINGS: dict[str, dict[str, str]] = {
    'User': {
        'chats': 'Chat',
        'skills': 'Skill',
        'resumes': 'Resume',
        'job_roles': 'JobRole',
    },
    'Skill': {
        'user': 'User',
        'aliases': 'SkillAlias',
        'job_skills': 'JobSkill',
    },
    'SkillAlias': {
        'skill': 'Skill',
    },
    'JobRole': {
        'user': 'User',
        'skills': 'JobSkill',
        'analyses': 'Analysis',
    },
    'JobSkill': {
        'job': 'JobRole',
        'skill': 'Skill',
    },
    'Resume': {
        'user': 'User',
        'analyses': 'Analysis',
        'enrichments': 'CandidateEnrichment',
    },
    'CandidateEnrichment': {
        'candidate': 'Resume',
    },
    'Analysis': {
        'job': 'JobRole',
        'resume': 'Resume',
    },
    'Chat': {
        'user': 'User',
        'messages': 'ChatMessage',
    },
    'ChatMessage': {
        'chat': 'Chat',
    },
}

# fmt: on